"""add_performance_indexes

Revision ID: 2329cfa66168
Revises: 61cbb76c0196
Create Date: 2026-07-23 13:08:58.008984

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '2329cfa66168'
down_revision: Union[str, None] = '61cbb76c0196'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_clusters_datasource_id', 'clusters', ['datasource_id'], unique=False)
    op.create_index('ix_datasources_user_created', 'datasources', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_messages_user_created', 'messages', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_messages_user_sentiment', 'messages', ['user_id', 'sentiment'], unique=False)
    op.create_index('ix_pipeline_jobs_datasource_created', 'pipeline_jobs', ['datasource_id', 'created_at'], unique=False)
    op.create_index('ix_tickets_user_created', 'tickets', ['user_id', 'created_at'], unique=False)
    op.create_index('ix_tickets_user_status', 'tickets', ['user_id', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tickets_user_status', table_name='tickets')
    op.drop_index('ix_tickets_user_created', table_name='tickets')
    op.drop_index('ix_pipeline_jobs_datasource_created', table_name='pipeline_jobs')
    op.drop_index('ix_messages_user_sentiment', table_name='messages')
    op.drop_index('ix_messages_user_created', table_name='messages')
    op.drop_index('ix_datasources_user_created', table_name='datasources')
    op.drop_index('ix_clusters_datasource_id', table_name='clusters')
    # ### end Alembic commands ###
