"""add_external_id_to_reviews

Revision ID: 61cbb76c0196
Revises: 685d368b6a66
Create Date: 2026-07-22 21:59:48.824368

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '61cbb76c0196'
down_revision: Union[str, None] = '685d368b6a66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('external_id', sa.String(), nullable=True))
    op.create_index('ix_reviews_datasource_external', 'reviews', ['datasource_id', 'external_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_reviews_datasource_external', table_name='reviews')
    op.drop_column('reviews', 'external_id')
    # ### end Alembic commands ###
