"""add_password_reset_columns_to_users

Revision ID: 685d368b6a66
Revises: 230a0afefba4
Create Date: 2026-07-22 21:11:40.974622

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '685d368b6a66'
down_revision: Union[str, None] = '230a0afefba4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reset_token_hash', sa.String(), nullable=True))
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token_hash')
    # ### end Alembic commands ###
