"""rag_foundation_pgvector_scrape_params_cluster_reviews

Revision ID: df8eba836231
Revises: 2329cfa66168
Create Date: 2026-07-23 14:09:27.034304

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

revision: str = 'df8eba836231'
down_revision: Union[str, None] = '2329cfa66168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Enable pgvector extension
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cluster_reviews',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('review_id', sa.String(), nullable=False),
    sa.Column('is_example', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['clusters.id'], ),
    sa.ForeignKeyConstraint(['review_id'], ['reviews.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cluster_reviews_cluster_id', 'cluster_reviews', ['cluster_id'], unique=False)
    op.create_index('ix_cluster_reviews_review_id', 'cluster_reviews', ['review_id'], unique=False)
    op.drop_column('clusters', 'examples')
    op.drop_column('clusters', 'sentiment_counts')
    op.drop_column('clusters', 'mentions_over_time')
    op.add_column('datasources', sa.Column('scrape_lang', sa.String(), nullable=True))
    op.add_column('datasources', sa.Column('scrape_country', sa.String(), nullable=True))
    op.add_column('datasources', sa.Column('scrape_count', sa.Integer(), nullable=True))
    op.add_column('reviews', sa.Column('language', sa.String(), nullable=True))
    op.add_column('reviews', sa.Column('embedding', Vector(384), nullable=True))
    op.create_index('ix_reviews_datasource_id', 'reviews', ['datasource_id'], unique=False)
    # HNSW index for fast approximate nearest-neighbour search on embeddings
    op.execute(
        "CREATE INDEX ix_reviews_embedding_hnsw ON reviews "
        "USING hnsw (embedding vector_cosine_ops) "
        "WITH (m = 16, ef_construction = 64)"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP INDEX IF EXISTS ix_reviews_embedding_hnsw")
    op.drop_index('ix_reviews_datasource_id', table_name='reviews')
    op.drop_column('reviews', 'embedding')
    op.drop_column('reviews', 'language')
    op.drop_column('datasources', 'scrape_count')
    op.drop_column('datasources', 'scrape_country')
    op.drop_column('datasources', 'scrape_lang')
    op.add_column('clusters', sa.Column('mentions_over_time', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('clusters', sa.Column('sentiment_counts', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('clusters', sa.Column('examples', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_index('ix_cluster_reviews_review_id', table_name='cluster_reviews')
    op.drop_index('ix_cluster_reviews_cluster_id', table_name='cluster_reviews')
    op.drop_table('cluster_reviews')
    # ### end Alembic commands ###
